import { StyleSheet } from 'react-native';

export const stylesreport = StyleSheet.create({
    // Contenedores principales
    container: {
        flex: 1,
        backgroundColor: '#f0f2f5',
        marginTop: -30,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    areaName: {
        fontSize: 16,
        color: '#ff006f',
        fontWeight: '600',
        marginLeft: 8,
        marginRight: 5,
        maxWidth: 220,
        flexShrink: 1, // Permite que se reduzca si es necesario
    },
    // Sección fija superior
    fixedSection: {
        backgroundColor: '#f0f2f5',
        zIndex: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 5,
        paddingVertical: 5,
    },
    header: {
        paddingVertical: 1,
        paddingHorizontal: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 30,
    },
    headerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#05aaca',
        paddingHorizontal: 15,
        paddingVertical: 5,
        borderRadius: 8,
    },
    buttonText: {
        color: 'white',
        fontWeight: '600',
        marginLeft: 8,
        fontSize: 14,
    },
    responsableInput: {
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        padding: 5,
        fontSize: 16,
        color: '#111827',
        marginLeft: 10,
        flex: 1,
    },
    infoItem: {
        marginBottom: 5,
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoCard: {
        flexDirection: 'row',
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginVertical: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        justifyContent: 'space-between',
    },
    infoLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 5,
    },
    infoValue: {
        fontSize: 16,
        color: '#111827',
        fontWeight: '500',
    },
    areaSection: {
        backgroundColor: 'white',
        marginHorizontal: 15,
        marginBottom: 5,
        padding: 8,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    areaHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    evaluationSubtitle: {
        fontSize: 14,
        color: '#6b7280',
    },
    areaScroll: {
        maxHeight: 100,
        minHeight: 50,
    },
    areaButton: {
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 8,
        paddingVertical: 8,
        borderRadius: 10,
        marginRight: 5,
        width: 100,
        position: 'relative',
    },
    areaButtonActive: {
        backgroundColor: '#ff006f',
    },
    areaIcon: {
        fontSize: 24,
        marginBottom: 5,
    },
    areaButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
        textAlign: 'center',
    },
    areaButtonTextActive: {
        color: 'white',
        fontWeight: 'bold',
    },
    areasScrollView: {
        flex: 1,
        backgroundColor: 'white',
        marginTop: 2,
        paddingHorizontal: 2,
    },
    formContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 10,
        marginBottom: 6,
        marginHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    formHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    formTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        flex: 1,
    },
    formActions: {
        flexDirection: 'row',
        gap: 8,
    },
    smallButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        gap: 6,
    },
    smallButtonText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '600',
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 6,
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        padding: 10,
        fontSize: 14,
        color: '#1F2937',
        backgroundColor: '#F9FAFB',
    },
    textArea: {
        minHeight: 100,
        textAlignVertical: 'top',
    },
    selectContainer: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        backgroundColor: '#F9FAFB',
        maxHeight: 200,
    },
    selectOption: {
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    selectOptionActive: {
        backgroundColor: '#3B82F6',
    },
    selectOptionText: {
        fontSize: 14,
        color: '#374151',
    },
    selectOptionTextActive: {
        color: 'white',
        fontWeight: '600',
    },
    gridContainer: {
        flexDirection: 'row',
        gap: 5,
        marginBottom: 16,
    },
    gridColumn: {
        flex: 1,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
    },
    sucursalButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        marginRight: 8,
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    sucursalButtonActive: {
        backgroundColor: '#3B82F6',
        borderColor: '#3B82F6',
    },
    sucursalButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#374151',
    },
    sucursalButtonTextActive: {
        color: 'white',
        fontWeight: '600',
    },
    loadingOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContent: {
        backgroundColor: 'white',
        padding: 30,
        borderRadius: 12,
        alignItems: 'center',
        width: '80%',
    },
    loadingText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginTop: 16,
        textAlign: 'center',
    }
});