import { Platform, StyleSheet } from "react-native";

export const stylestemplateReminders = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    backButton: {
        backgroundColor: '#ff006f',
        padding: 8,
        borderRadius: 8,
    },
    title: {
        flex: 1,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginLeft: 16,
    },
    addButton: {
        backgroundColor: '#2196F3',
        padding: 8,
        borderRadius: 8,
    },
    templateItem: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginBottom: 12,
        borderRadius: 12,
        padding: 16,
        elevation: 2,
    },
    templateItemActive: {
        borderLeftWidth: 4,
        borderLeftColor: '#4CAF50',
    },
    templateItemHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    templateInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    templateIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#2196F3',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    templateText: {
        flex: 1,
    },
    templateNombre: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    templateDescripcion: {
        fontSize: 14,
        color: '#666',
        marginBottom: 4,
    },
    templateDetalles: {
        fontSize: 12,
        color: '#888',
    },
    templateActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    deleteButton: {
        padding: 4,
        marginRight: 8,
    },
    variablesPreview: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    variablesTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: '#666',
        marginBottom: 4,
    },
    variablesText: {
        fontSize: 11,
        color: '#888',
        fontFamily: 'monospace',
    },
        inputError: {
        borderColor: '#ff4444',
        borderWidth: 2,
    },
    errorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    errorText: {
        color: '#ff4444',
        fontSize: 12,
        marginLeft: 4,
    },
    warningContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        padding: 8,
        backgroundColor: '#FFF3E0',
        borderRadius: 4,
        borderLeftWidth: 4,
        borderLeftColor: '#FF9800',
    },
    warningText: {
        color: '#FF9800',
        fontSize: 12,
        marginLeft: 4,
        flex: 1,
    },
    characterCounter: {
        fontSize: 12,
        color: '#999',
    },
    characterCounterError: {
        color: '#ff4444',
        fontWeight: 'bold',
    },
    inputHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    previewContainer: {
        marginTop: 16,
        padding: 12,
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    previewTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    previewContent: {
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    previewText: {
        fontSize: 13,
        color: '#333',
        lineHeight: 18,
    },
    validationSummary: {
        marginTop: 16,
        padding: 12,
        backgroundColor: '#f0f7ff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#bbdefb',
    },
    validationTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1976d2',
        marginBottom: 8,
    },
    validationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    validationText: {
        fontSize: 13,
        color: '#333',
        marginLeft: 8,
    },
    formatHelp: {
        fontSize: 11,
        color: '#666',
        marginTop: 4,
        fontStyle: 'italic',
    },
    variablePreview: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#E8F5E9',
        borderRadius: 8,
    },
    variablePreviewTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#2E7D32',
        marginBottom: 8,
    },
    variablePreviewContent: {
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    variablePreviewText: {
        fontSize: 14,
        color: '#333',
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    saveButtonDisabled: {
        backgroundColor: '#ccc',
        opacity: 0.7,
    },
    textAreaSmall: {
        minHeight: 60,
        maxHeight: 100,
    },
    headerItem: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        marginBottom: 8,
        padding: 12,
    },
    headerItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerItemIcon: {
        marginRight: 12,
    },
    headerItemInfo: {
        flex: 1,
    },
    headerItemName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 2,
    },
    headerItemDetails: {
        fontSize: 12,
        color: '#666',
    },
    emptyHeaders: {
        alignItems: 'center',
        padding: 24,
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
    },
    emptyHeadersText: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        marginTop: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        width: '100%',
        maxHeight: '80%',
    },
    smallModal: {
        maxHeight: '60%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    modalContent: {
        padding: 16,
    },
    modalFooter: {
        flexDirection: 'row',
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        gap: 12,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 6,
    },
    input: {
        backgroundColor: '#f8f9fa',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        color: '#333',
    },
    inputHelp: {
        fontSize: 12,
        color: '#666',
        marginBottom: 6,
    },
    tipoButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    tipoButton: {
        flex: 1,
        padding: 12,
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    tipoButtonActive: {
        backgroundColor: '#2196F3',
        borderColor: '#2196F3',
    },
    tipoButtonText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '600',
    },
    tipoButtonTextActive: {
        color: '#fff',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    addSmallButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    addSmallButtonText: {
        color: '#2196F3',
        fontSize: 14,
        fontWeight: '600',
    },
    cancelButton: {
        flex: 1,
        padding: 14,
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    saveButton: {
        flex: 1,
        padding: 14,
        backgroundColor: '#2196F3',
        borderRadius: 8,
        alignItems: 'center',
    },
    saveButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    loadingText: {
        fontSize: 16,
        color: '#666',
        marginTop: 16,
    },
    listContainer: {
        paddingVertical: 16,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#666',
        marginTop: 16,
    },
    emptySubtext: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        marginTop: 8,
    },
});